licenses(["notice"]) # Apache 2.0

package(default_visibility = ["//mediapipe/examples:__subpackages__"])

cc_binary(
    name = "winner_face_keypoint_cpu",
    deps = [
        "//mediapipe/examples/desktop:demo_run_graph_main",
        "//mediapipe/graphs/winner_face_keypoint:desktop_simple_flow_calculators",
    ],
)