cc_library(
    name = "example",
    srcs = ["example.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework:calculator_framework",
    ],
    alwayslink = 1,
)

cc_library(
    name = "log_input_calculator",
    srcs = ["log_input_calculator.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework/api2:node",
        "//mediapipe/framework:calculator_framework",
    ],
    alwayslink = 1,
)