# MediaPipe graph that performs face mesh on desktop with TensorFlow Lite
# on CPU.

input_side_packet: "input_image_path"
input_side_packet: "output_image_path"

# max_queue_size limits the number of packets enqueued on any input stream
# by throttling inputs to the graph. This makes the graph only process one
# frame per time.
max_queue_size: 1

# Decodes an input video file into images and a video header.
node {
  calculator: "OpenCvVideoDecoderCalculator"
  input_side_packet: "INPUT_FILE_PATH:input_image_path"
  output_stream: "VIDEO:input_image"
  output_stream: "VIDEO_PRESTREAM:input_video_header"
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE:input_image"
  output_stream: "SIZE:size"
}

node {
  calculator: "LogInputCalculator"
  input_stream: "SIZE:size"
}

node {
  calculator: "FaceGeometryEnvGeneratorCalculator"
  output_side_packet: "ENVIRONMENT:environment"
  node_options: {
    [type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions] {
      environment: {
        origin_point_location: TOP_LEFT_CORNER
        perspective_camera: {
          vertical_fov_degrees: 63.0  # 63 degrees
          near: 1.0  # 1cm
          far: 10000.0  # 100m
        }
      }
    }
  }
}

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "input_image"
  output_stream: "input_image_gpu"
}

node {
  calculator: "SingleFaceGeometryFromLandmarksGpu"
  input_stream: "IMAGE:input_image_gpu"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
}